dole_app_exercise/app/home/forms.py
# from flask_wtf import FlaskForm
# from flask_wtf.file import FileField, FileRequired
# from wtforms import SubmitField

# class UploadForm(FlaskForm):
#     file = FileField('File', validators=[FileRequired()])

dole_app_exercise/app/home/__init__.py
from flask import Blueprint

home = Blueprint('home', __name__)

from . import views

dole_app_exercise/app/home/views.py
from flask import render_template, redirect, url_for, request, flash
from markupsafe import Markup

from app.models import User, Department, Tenure
from . import home as home_blueprint
import os
import asyncio
from app.helpers import process_excel_file
# from .forms import CourseForm
from app import database
# import threading
# import concurrent.futures


@home_blueprint.route('/user/<int:user_id>', methods=['GET'])
def user_detail(user_id):
    user = User.query.get(user_id)
    # departments = Department.query.all()
    # department_years = [(department.name, user.get_years_in_department(department)) for department in departments]
    total_years = user.total_tenure()
    # dept_tenure_dict = {department.name: department.get_total_tenure()[department.name] for department in departments}
    # dept_tenure_list = [(department.name, sum([tenure.years for tenure in department.tenures])) for department in departments]
    return render_template('home/user_detail.html',
                            user=user,
                        #     department_years=department_years, 
                           total_years=total_years,
                        #    dept_tenure_dict=dept_tenure_dict, 
                        #    dept_tenure_list=dept_tenure_list
                           )




# @home_blueprint.route('/user/<int:user_id>')
# def user_detail(user_id):
#     user = User.query.get(user_id)
#     if not user:
#         flash('User not found!', 'error')
#         return redirect(url_for('home.all_users'))
#     return render_template('home/user_detail.html', user=user)

# @home_blueprint.route('/user/<int:user_id>', methods=['GET'])
# def user_detail(user_id):
#     user = User.query.get(user_id)
#     departments = Department.query.all()
#     department_years = [(department.name, user.get_years_in_department(department)) for department in departments]
#     total_years = user.get_total_tenure()
#     dept_tenure_dict = {department.name: department.get_total_tenure()[department.name] for department in departments}
#     dept_tenure_list = [(department.name, sum([tenure.years for tenure in department.tenures])) for department in departments]
#     return render_template('home/user_detail.html', user=user, department_years=department_years, 
#                            total_years=total_years, dept_tenure_dict=dept_tenure_dict, 
#                            dept_tenure_list=dept_tenure_list)



# @home_blueprint.route('/user/<int:user_id>', methods=['GET'])
# def user_detail(user_id):
#     user = User.query.get(user_id)
#     departments = Department.query.all()
#     department_years = []
#     total_years = 0
#     for department in departments:
#         years = user.get_years_in_department(department)
#         department_years.append((department.name, years))
#         total_years += years
#     # calculate total company tenure
#     company_tenure = user.get_total_tenure()
#     # create dictionary of department and tenure
#     dept_tenure_dict = {}
#     for department in departments:
#         tenure = Department.get_total_tenure(department)
#         dept_tenure_dict[department.name] = tenure
#     # create a list of tuples containing department and total tenure for all employees
#     dept_tenure_list = [(department.name, department.get_total_tenure()) for department in departments]
#     return render_template('home/user_detail.html', user=user, department_years=department_years, 
#                            total_years=total_years, company_tenure=company_tenure,
#                            dept_tenure_dict=dept_tenure_dict, dept_tenure_list=dept_tenure_list)



@home_blueprint.route('/all/users', methods=['GET', 'POST'])
def all_users():
    if request.method == 'POST':
        excel_file = request.files['file']
        if not excel_file:
            flash('File has to be an excel file!', 'error')
            return redirect(url_for('home.all_users'))
        if not excel_file.filename:
            flash('File name can not be empty', 'error')
            return redirect(url_for('home.all_users'))
        if excel_file.filename.split('.')[-1] not in ['xls', 'xlsx']:
            flash('Invalid file type', 'error')
            return redirect(url_for('home.all_users'))
        
        if len(excel_file.read()) > 1024 * 1024:
            flash('File size exceeds 1MB', 'error')
            return redirect(url_for('home.all_users'))

        # executor = concurrent.futures.ThreadPoolExecutor()
        # executor.submit(process_excel_file, excel_file)
        # executor.shutdown(wait=True)

        asyncio.run(process_excel_file(excel_file))

        flash('File is being uploaded please refresh page in a few seconds', 'success')
        return redirect(url_for('home.all_users'))
    
    # delete_all()
    all_users = User.query.all()

    return render_template('home/home.html',
                           users=all_users,
                           title="Users",)




def delete_all():

    dept = Department.query.all()
    ten = Tenure.query.all()
    all_users = User.query.all()
    for t in ten:
        print(t, 123)
        database.session.delete(t)
        database.session.commit()
    for d in dept:
        database.session.delete(d)
        database.session.commit()
    for us in all_users:
        database.session.delete(us)
        database.session.commit()
    

dole_app_exercise/app/templates/home/home.html
{% extends "base.html" %}

{% set active_page = "dashboard" %}

{% block title %}Dashboard{% endblock %}

{% block content %}
{% include "components/navbar.html" %}


{% with messages = get_flashed_messages() %}
{% if messages %}
<div class="alert alert-info">
  <ul class="list-unstyled">
  {% for message in messages %}
    <li>{{ message }}</li>
  {% endfor %}
  </ul>
</div>
{% endif %}
{% endwith %}


<div class="container mt-3">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card">
                <div class="card-header">
                    <h4 class="text-center">Upload a File</h4>
                </div>
                <div class="card-body">
                  
                    <form action="/home/all/users" method="POST" enctype="multipart/form-data">
                        <div class="mb-3">
                            <label for="file" class="form-label">Select File:</label>
                            <input type="file" class="form-control-file" id="file" name="file">
                        </div>
                        <div class="text-center">
                            <button type="submit" class="btn btn-primary"><i class="fa fa-upload"></i> Upload</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>





<div class="container">
    <div class="row mt-3">
      <div class="col">
        <h3 class="mb-3">All Users</h3>
        {% if users|length > 0 %}
        <div class="table-responsive">
          <table class="table table-hover">
            <thead>
              <tr>
                <th scope="col">User ID</th>
                <th scope="col">Name</th>
                <th scope="col">Salary</th>
                <th scope="col">Date Joined</th>
              </tr>
            </thead>
            <tbody>
              {% for user in users %}
              <tr class='clickable-row'>
                <td>{{ user.id }}</td>
                <td>{{ user.name }}</td>
                <td>{{ user.time_created.strftime('%Y/%m/%d') }}</td>
<td><a href="{{ url_for('home.user_detail', user_id=user.id) }}" class="btn btn-primary">View user details</a></td>
              </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>
        {% else %}
        <div class="text-center empty-table mt-3" style="display: block;">No Users to display</div>
        {% endif %}
      </div>
    </div>
  </div>

  

<!-- add dashboard-specific content here -->
{% endblock %}

dole_app_exercise/app/templates/home/user_detail.html
<h2>{{ user.name }}</h2>
<h3>Years per unit:</h3>

<ul>
{% for tenure in user.tenures %}
    <li>{{ tenure.department.name }}: {{ tenure.years }}</li>
{% endfor %}


<h3>Years per unit: {{total_years}}</h3>

<canvas id="myChart"></canvas>



</ul>

dole_app_exercise/app/templates/home/users.html
{% extends "base.html" %}

{% set active_page = "home" %}

{% block title %}All Users{% endblock %}

{% block content %}
<div class="panel-list">
    <h3 class="ml-2 mt-3">All Users</h3>
    <div class="row row-content">
        <div class="col-12">
            <h4>{{ Users }}</h4>
        </div>

        <div class="table-responsive-sm col-12">
            {% if users|length > 0 %}
            <table class="table table-sm table-panel table-desktop">
                <thead>
                <tr>
                    <th scope="col th-sm">#</th>
                    <th scope="col th-sm">User ID</th>
                    <th scope="col th-sm">Name</th>
                    <th scope="col th-sm">Salary</th>
                    <th scope="col th-sm">Date Joined</th>
                </tr>
                </thead>
                <tbody>
                {% for user in users %}
                <tr class='clickable-row'>
                    <th scope="row">{{ loop.index }}</th>
                    <td>{{ user.id }}</td>
                    <td>{{ user.name }}</td>
                    <td>{{ user.salary }}</td>
                    <td>{{ user.time_created.strftime('%Y/%m/%d') }}</td>
                </tr>
                {% endfor %}
                </tbody>
            </table>

            {% else %}
            <div class="text-center empty-table" style="display: block;">No Users to display</div>
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}